### ISSUE TITLE
Failed to load the Dyslexia package

### ISSUE THREAD

**Issue by picibucor** [thiagopnts/dyslexia#1]
I Just started atom and a "Failed to load the Dyslexia package" Pop-up appeared.

**Atom Version**: 1.0.0
**System**: xxx-1
**Thrown From**: [Dyslexia](https://github.com/thiagopnts/dyslexia) package, v0.0.3
### Stack Trace

Failed to load the Dyslexia package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (C:\Users\xxx\.atom\packages\Dyslexia\lib\dyslexia-view.coffee:4:199)
    at C:\Users\xxx\.atom\packages\Dyslexia\lib\dyslexia-view.coffee:9:5
    at Object.<anonymous> (C:\Users\xxx\.atom\packages\Dyslexia\lib\dyslexia-view.coffee:23:5)
    at Object.<anonymous> (C:\Users\xxx\.atom\packages\Dyslexia\lib\dyslexia-view.coffee:25:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\xxx\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-runner, v2.4.1
autocomplete-paths, v1.0.2
autocomplete-python, v0.5.1
color-picker, v2.0.7
Dyslexia, v0.0.3
file-icons, v1.5.8
highlight-line, v0.11.0
linter, v1.1.0
linter-pep257, v0.2.1
linter-pep8, v0.2.0
linter-pylint, v0.2.2
linter-python-pyflakes, v0.1.0
minimap, v4.10.1
minimap-bookmarks, v0.1.0
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.2.0
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
navigate, v0.1.6
project-colorize, v0.2.0
python-isort, v0.0.7

# Dev
No dev packages
```

**Comment by thiagopnts** [comment]
I guess Atom changed its API, I'm gonna check this later when I have some time, PRs are also welcome.
